/** 
 * Just for testing purpose
 * apexClass is the class to analyse
 * symbolTable contains symbol Table using tooling api - select name , SymbolTable from apexclass where id = '01p0900000E5uVVAAZ' -
 * */ 

module.exports = { 
		apexClass: 'public class dependencyClass {\n    String Industry;\n    SObjectField field \t= Lead.Industry;\n    Lead myGlobalLead;\n    Account myGlobalAccount;\n    //Yet another comment\n    /*SObjectField field \t= Lead.Industry\n\t/*this is some comment in two line\n\tSObjectField field \t= Lead.Industry*/\n    public static void firstMethod(){\n        //SObjectField field \t\t\t= Lead.Industry;\n        List<Lead> myLeadList \t\t= [select id , industry from Lead];\n        Map<Id, Lead> myLeadMap\t\t= new Map<Id, Lead>();\n        Campaign mycampaign\t\t\t= [select id , My_Lead__r.industry from Campaign][0];\n        //String ind\t\t\t\t\t= myLeadList[0].Industry;\n        Lead a \t\t\t\t\t\t= new Lead(Industry=\'Auto\');\n        a.Industry \t\t\t\t\t= null;\n        a.CleanStatus\t\t\t\t= null;\n        a.ProductInterest__c\t\t= null;\n        //String Industry; //random variable with the same name\n        //SObjectField field = Account.Industry;// actually a field but WRONG object\n        //String IndustryValue;//variable that matches on a part of the name\n        //List<Lead> l = [SELECT Industry_Field__c FROM Lead];//correct object but wrong field, because the name matches\n        //Account notALead = new Account();\n        //notALead.Industry = \'gotcha\';//actually a field but wrong object again\n        //Lead myLead = new Lead();\n        //String Industry;//this will return a false positive\n    }\n',
		symbolTable: '{ "size": 1, "totalSize": 1, "done": true, "queryLocator": null, "entityTypeName": "ApexClass", "records": [ { "attributes": { "type": "ApexClass", "url": "/services/data/v50.0/tooling/sobjects/ApexClass/01p0900000E5uVVAAZ" }, "Name": "dependencyClass", "SymbolTable": { "constructors": [], "externalReferences": [], "id": "dependencyClass", "innerClasses": [], "interfaces": [], "key": "dependencyClass", "methods": [ { "annotations": [], "location": { "column": 24, "line": 10 }, "modifiers": [ "static", "public" ], "name": "firstMethod", "parameters": [], "references": [], "returnType": "void", "type": null } ], "name": "dependencyClass", "namespace": null, "parentClass": "", "properties": [ { "annotations": [], "location": { "column": 12, "line": 2 }, "modifiers": [ "private" ], "name": "Industry", "references": [], "type": "String" }, { "annotations": [], "location": { "column": 18, "line": 3 }, "modifiers": [ "private" ], "name": "field", "references": [], "type": "Schema.SObjectField" }, { "annotations": [], "location": { "column": 10, "line": 4 }, "modifiers": [ "private" ], "name": "myGlobalLead", "references": [], "type": "Lead" }, { "annotations": [], "location": { "column": 13, "line": 5 }, "modifiers": [ "private" ], "name": "myGlobalAccount", "references": [], "type": "Account" } ], "tableDeclaration": { "annotations": [], "location": { "column": 14, "line": 1 }, "modifiers": [ "public" ], "name": "dependencyClass", "references": [], "type": "dependencyClass" }, "variables": [ { "annotations": [], "location": { "column": 20, "line": 12 }, "modifiers": [], "name": "myLeadList", "references": [], "type": "List<Lead>" }, { "annotations": [], "location": { "column": 23, "line": 13 }, "modifiers": [], "name": "myLeadMap", "references": [], "type": "Map<Id,Lead>" }, { "annotations": [], "location": { "column": 18, "line": 14 }, "modifiers": [], "name": "mycampaign", "references": [], "type": "Campaign" }, { "annotations": [], "location": { "column": 14, "line": 16 }, "modifiers": [], "name": "a", "references": [], "type": "Lead" } ] } } ] }'
}