/** 
 * Just for testing purpose
 * apexClass is the class to analyse
 * symbolTable contains symbol Table using tooling api - select name , SymbolTable from apexclass where id = '01p0900000E5uVVAAZ' -
 * */ 

module.exports = { 
		apexClass: 'public class testingSingleCases {\n    private static Lead myGlobalLead;\n    private static String Industry;\n    //private static List<Account> accList = [select id, name, createddate from account];\n    \n    private static void getNothing(){\n        //accList = [select id, name, createddate from account];\n        List<Account> accList2\t\t= [select id, (select id, account.Parent.name, name from contacts) from account];\n        List<Lead> leadList = [select id, name, industry from lead];\n        String test =leadList[0].industry;\n        List<OpportunityLineItem> oppLineItemsList = [select id, customOppLookup__r.name, customOppLookup__r.account.name from OpportunityLineItem];\n    \tString ind = [select id, industry from lead ][0].industry;\n    }\n}',
		symbolTable: '{ "size": 1, "totalSize": 1, "done": true, "queryLocator": null, "entityTypeName": "ApexClass", "records": [ { "attributes": { "type": "ApexClass", "url": "/services/data/v49.0/tooling/sobjects/ApexClass/01p0900000FegelAAB" }, "Name": "testingSingleCases", "SymbolTable": { "constructors": [], "externalReferences": [], "id": "testingSingleCases", "innerClasses": [], "interfaces": [], "key": "testingSingleCases", "methods": [ { "annotations": [], "location": { "column": 25, "line": 6 }, "modifiers": [ "private", "static" ], "name": "getNothing", "parameters": [], "references": [], "returnType": "void", "type": null } ], "name": "testingSingleCases", "namespace": null, "parentClass": "", "properties": [ { "annotations": [], "location": { "column": 25, "line": 2 }, "modifiers": [ "private", "static" ], "name": "myGlobalLead", "references": [], "type": "Lead" }, { "annotations": [], "location": { "column": 27, "line": 3 }, "modifiers": [ "private", "static" ], "name": "Industry", "references": [], "type": "String" } ], "tableDeclaration": { "annotations": [], "location": { "column": 14, "line": 1 }, "modifiers": [ "public" ], "name": "testingSingleCases", "references": [], "type": "testingSingleCases" }, "variables": [ { "annotations": [], "location": { "column": 23, "line": 8 }, "modifiers": [], "name": "accList2", "references": [], "type": "List<Account>" }, { "annotations": [], "location": { "column": 20, "line": 9 }, "modifiers": [], "name": "leadList", "references": [], "type": "List<Lead>" }, { "annotations": [], "location": { "column": 16, "line": 10 }, "modifiers": [], "name": "test", "references": [], "type": "String" }, { "annotations": [], "location": { "column": 35, "line": 11 }, "modifiers": [], "name": "oppLineItemsList", "references": [], "type": "List<OpportunityLineItem>" }, { "annotations": [], "location": { "column": 13, "line": 12 }, "modifiers": [], "name": "ind", "references": [], "type": "String" } ] } } ] }'
}